### ISSUE TITLE
Build LilyGo T-PicoC3 error: Invalid MICROPY_BOARD specified: LILYGO_T_PicoC3

### ISSUE THREAD

**Issue by FreddyBI** [Xinyuan-LilyGO/lilygo-micropython#18]
Hello,

T-PicoC3
$ cp config_T-PicoC3 config
$ sudo apt install gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
$ make

How resolve this problem?

![image](https://user-images.githubusercontent.com/71754323/196165906-da759f2e-17a1-4b00-9c3a-35a35ca76c40.png)

**Comment by liangyingy** [comment]
```shell
sudo apt-get install git make python3 python3-pip cmake quilt
rm build_dir -rf
make
```

**Comment by FreddyBI** [comment]
Thanks for help.

sudo apt-get install git make python3 python3-pip cmake quilt
rm build_dir -rf
make
-->  now other Build error
![Untitled1](https://user-images.githubusercontent.com/71754323/196431625-cb02d65c-9e5b-4de9-8a7c-590a81c959d8.jpg)
![Untitled2](https://user-images.githubusercontent.com/71754323/196432079-72c9d57a-440c-4aec-9468-a9599a995cca.jpg)
![Untitled3](https://user-images.githubusercontent.com/71754323/196432607-3169889d-417c-40d4-a843-0c6c3321ed0a.jpg)

**Comment by FreddyBI** [comment]
Hello,
I renstal all.
And now build is ok.
Thanks.
