### ISSUE TITLE
Build failure Invalid Micropy_board Lilygo_T-SIM7000G

### ISSUE THREAD

**Issue by rwslippey** [Xinyuan-LilyGO/lilygo-micropython#20]
Just getting started with the board and trying to use micropython, getting a build failure though.
```
CMake Error at CMakeLists.txt:18 (message):
  Invalid MICROPY_BOARD specified: LILYGO_T-SIM7000G
```

**Comment by liangyingy** [comment]
![image](https://user-images.githubusercontent.com/46518962/198434857-29630703-bad4-4fa6-972d-91a2d86165bf.png)

**Comment by rwslippey** [comment]
> ![image](https://user-images.githubusercontent.com/46518962/198434857-29630703-bad4-4fa6-972d-91a2d86165bf.png)

Will double check to make sure they installed but I did install the prerequisites per the documentation. Will report back later on today when I get home.

**Comment by rwslippey** [comment]
Ok, an update here. Ive managed to get the build to work. Turns out a package failed to install first run and I missed it.

Next question, is there any documentation aside from this [old code example](https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7000G/tree/master/examples/MicroPython_LoBo), which isn't working currently with this build. Really, I'm just looking for where to start, network connection, gps, etc

**Comment by besi** [comment]
I got the same error on a mac and all I need to get it to work was install quilt:

	brew install quilt
