### ISSUE TITLE
SD card not recognized

### ISSUE THREAD

**Issue by scumola** [Xinyuan-LilyGO/lilygo-micropython#3]
I bought the SD card adapter and inserted a brand new FAT-formatted 32GB SD card, but when I try to access the card, I get:

```
>>> import machine
>>> sd = machine.SDCard()
  Traceback (most recent call last):
    File <stdin>, line 1, in <module>
  OSError: (-259, 'ESP_ERR_INVALID_STATE')
>>> 
```

I tried 3 different brand new SD cards.

**Comment by scumola** [comment]
This is the official lillygo adapter I'm using

![image](https://user-images.githubusercontent.com/386016/156030111-640d3e4f-a393-4328-8c59-ffa5a162ef64.png)

**Comment by liangyingy** [comment]
I don't have a 32GB SD card on hand, the following code works fine on a 16GB SD card:

```python
import machine
import os

sd = machine.SDCard(slot = 2, width = 1, sck = 14, miso = 12, mosi = 13, cs = 15)

sd.info()
os.mount(sd, "/sd")
os.listdir('/sd')
```

**Comment by scumola** [comment]
I added SKIPSD to / so micropython doesn't try to boot off the SD card and it works!

Bug: any kind of guru meditation error (like the framebuffer crashes) kills micropython and makes it unresponsive even with multiple power cycles until I physically unplug the SD card adapter and reboot the board.

**Comment by He-Peter-Huang** [comment]
I'm using the LilyGo T-RGB, I'm having trouble setting up the SDCard, the CS pin is connected to P07 on the XL9535. What should I put in for the SDCard cs parameter?
